export const dataRows = [
  {
    id: 1,
    username: "Jon Snow",
    firstName: "Jon",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Vanshi",
    firstName: "Vanshika",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Anshu",
    firstName: "Anshika",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Tima",
    firstName: "Amit",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Vanshi",
    firstName: "Vanshika",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Vanshi",
    firstName: "Vanshika",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Vanshi",
    firstName: "Vanshika",
    avatar: "/main_avatar.jpg",
    email: "vanshikabansal@gmail.com",
    status: "active",
    transaction: "$120.00",
  }
];
